// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

// GET /currencies and POST /conversions are both enforced at the API
// gateway from openapi.yaml's `security` block (sign-in for the former, the
// `conversions:create` scope for the latter) — see the `ballerina` and
// `api-management` skills. Neither resource needs the caller's identity for
// its own logic (the currency list is the same for everyone, and a
// conversion is not a per-user resource), so neither reads the gateway
// caller here. The service is still `InterceptableService` so the signed
// assertion is verified whenever one is present.
service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    # The curated list of supported currencies
    #
    # + return - returns can be any of following types
    # http:Ok (Supported currencies)
    # http:Unauthorized (Not signed in)
    resource function get currencies() returns inline_response_200|ErrorUnauthorized {
        return {
            count: CURRENCIES.length(),
            next: (),
            previous: (),
            data: CURRENCIES
        };
    }

    # Convert an amount from one supported currency to another
    #
    # + return - returns can be any of following types
    # http:Ok (The converted amount and rate used)
    # http:BadRequest (Invalid currency pair or amount)
    # http:Unauthorized (Not signed in)
    resource function post conversions(@http:Payload ConversionRequest payload) returns ConversionOk|ErrorBadRequest|ErrorUnauthorized|error {
        Currency? sourceCurrency = findCurrency(payload.sourceCurrency);
        if sourceCurrency is () {
            return <ErrorBadRequest>{body: {code: 400, message: "unsupported sourceCurrency"}};
        }
        Currency? targetCurrency = findCurrency(payload.targetCurrency);
        if targetCurrency is () {
            return <ErrorBadRequest>{body: {code: 400, message: "unsupported targetCurrency"}};
        }
        if payload.amount <= 0d {
            return <ErrorBadRequest>{body: {code: 400, message: "amount must be a positive number"}};
        }

        Conversion conversion = check convertAmount(sourceCurrency.code, targetCurrency.code, payload.amount);
        return <ConversionOk>{body: conversion};
    }
}

public type ConversionOk record {|
    *http:Ok;
    Conversion body;
|};

public type Currency record {
    # ISO 4217 currency code
    string code;
    # display name
    string name;
    # currency symbol
    string symbol;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Currency[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ConversionRequest record {
    # ISO 4217 code to convert from
    string sourceCurrency;
    # ISO 4217 code to convert to
    string targetCurrency;
    # amount in the source currency
    decimal amount;
};

public type Conversion record {
    # ISO 4217 code converted from
    string sourceCurrency;
    # ISO 4217 code converted to
    string targetCurrency;
    # amount in the source currency
    decimal amount;
    # exchange rate applied
    decimal rate;
    # amount in the target currency
    decimal convertedAmount;
    # when the rate was fetched
    string convertedAt;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
